Update master branch
Cray-HPE/console-node pull request #36
Opened 2022-01-28 16:29 UTC by mharding-hpe

Pull in the latest contents of the 1.2 branch into master

2022-01-28 19:47 UTC, rkleinman-hpe approved these changes

2022-02-07 15:52 UTC, ecozzi-hpe approved these changes

2022-02-15 16:28 UTC, jsollom-hpe requested changes

2022-02-15 16:28 UTC, jsollom-hpe commented on kubernetes/cray-console-node/values.yaml
> +        tag: latest
It is most convenient from an ease of upgrade standpoint to go with latest. However, I think it is ill-advised to do so from a stability standpoint. If the latest Alpine breaks something, then we have to figure out that the Alpine change is what broke us. We should pin to a specific trusted version.

2022-02-15 16:28 UTC, jsollom-hpe commented on kubernetes/cray-console-node/values.yaml
> +    tag: latest
See earlier comment about using the 'latest' tag. Don't be trendy, Mitch.

2022-02-15 16:28 UTC, jsollom-hpe commented on zypper-refresh-patch-clean.sh
> +#                  ACHTUNG!                    #
Achtung, baby!

2022-03-08 15:00 UTC, merged