Release/2.0.0
Cray-HPE/console-node pull request #78
Opened 2023-03-27 18:48 UTC by jesseviola-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

This introduces a dependency that is non-backwards compatible with console-operator <1.7.0

 - CASMCMS-8252: Enabled building of unstable artifacts
 - CASMCMS-8252: Updated header of update_versions.conf to reflect new tool options
 - CASMCMS-7169: Conman will be restarted if there is a change to the credentials
 - CASMCMS-7167: Implementing location api for pod location data to filter through console data
 - CASMCMS-8252: Update Chart with correct image and chart version strings during builds.

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

Backwards incompatible with console-operator <1.7.0

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves CASMCMS-8252
* Resolves CASMCMS-7169
* Resolves CASMCMS-7167
* Resolves CASMCMS-8252
* Documentation changes required in [issue id](issue link)
* Merge after https://github.com/Cray-HPE/console-operator/pull/50

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `mug`

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-03-29 19:11 UTC, dlaine-hpe requested changes
A couple of comments.

2023-03-29 19:11 UTC, dlaine-hpe commented on src/console_node/consoleNodeMain.go
> +	log.Panicf("Error: Failed to retrieve location from console-operator")
A different service failing to respond is no reason to crash this one. You get an entire cascade of failing services that way. Better to log the failure to connect and try in an infinite loop.

2023-03-29 19:11 UTC, dlaine-hpe commented on src/console_node/operator.go
> +	if sc != 200 && err == nil {
If the return code is not 200, shouldn't the err not be nil?

2023-04-06 19:55 UTC, rbak-hpe approved these changes

2023-04-07 14:53 UTC, dlaine-hpe approved these changes

2023-04-07 22:57 UTC, merged